### ISSUE TITLE
change wallet to also encrypt transactions with 'public' key

### ISSUE THREAD

**Issue by ghost** [p9c/pod#106]
Even to the time of writing the btcsuite/btcwallet used to build a wallet for this project the planned implementation of encrypting the transaction data hasn't been done.

At least, we must look at how much work this will entail because all of the database should be encrypted, even its structure really.

**Comment by l0k18** [comment]
the gui uses the public data encryption key and adds more encrypted data in separate files that it uses. There is still the need to implement the remaining encryption for some of the data in the wallet.

**Comment by l0k18** [comment]
currently this works with a text password but change it to a numeric code *or* password and create a shuffling input panel
