### ISSUE TITLE
create domain specific language for Gio

### ISSUE THREAD

**Issue by l0k18** [p9c/pod#45]
slice of interface with types associated with functions that parse the parameters. It is not for the base creation of the function but to be able to simplify the render tree logic

**Comment by stalker-loki** [comment]
This has been done, much more concise and condensed code can now be written and functions triggered by events can be inlined.

The commit that sees the final draft ready for testing is here, a few more tests need to be written and it is done.

https://github.com/p9c/pod/commit/f5eb0e963b9881f26e57ddb018c23f3b156ad93c

**Comment by stalker-loki** [comment]
final state is in here https://github.com/p9c/pod/commit/49d7789200a139505fb5e4608df9aee2a97ef90a
