### ISSUE TITLE
rewrite controller -> kopach -> worker command protocol

### ISSUE THREAD

**Issue by l0k18** [p9c/pod#61]
previous stdconn/worker runs a client-server communication topology meaning no interactive two way messaging. For the monitor to read logs this channel has to be bidirectional so a duplex pipe has been written that either side can send arbitrary messages instead of a call/reply in one direction and no possibility to initiate action the other way (or deliver information).

**Comment by l0k18** [comment]
Putting on the back burner, the logger protocol has been created but the miner and miner worker don't use it yet. This needs to be done because this protocol is more maintainable and flexible than using net/rpc which locks a client/server pattern into the protocol. Currently the logger is also not compatible with the net/rpc protocols so when they are fixed there will be more flexibility for everything as the duplex push pipe pattern can emulate client-server and model network connections as well.

**Comment by stalker-loki** [comment]
This is actually already done lol
