### ISSUE TITLE
bake in commit, branch and and tag to binary for various uses

### ISSUE THREAD

**Issue by l0k18** [p9c/pod#65]
one of them being generating correct to-the-current-state of a branch to show the github or whatever source view page, also to put on the version and to include it in the header of log files

**Comment by stalker-loki** [comment]
looks like goreleaser is the wtg for this, need to configure to put them into a central version function, also remove the old separate ones in wallet and node set them to use the same one

**Comment by l0k18** [comment]
this has been done with the 'stroy' (cmd/podbuild)
