### ISSUE TITLE
Add github action to build and test go project

### ISSUE THREAD

**Issue by stalker-loki** [p9c/pod#68]

**Comment by stalker-loki** [comment]
For this there may need to be some things done to deal with the Gio library so for this to revise and complete the 'headless' tag so it can be set to build without any Gio dependencies.

**Comment by saniales** [comment]
regarding gio I am discussing on dev slack gophers

**Comment by stalker-loki** [comment]
it should be possible I will do some looking now to get the ci working with minimal differences

**Comment by stalker-loki** [comment]
the CI is now running and tests fail so now there is some clear work to be done
